### ISSUE TITLE
项目引入并启动时报错

### ISSUE THREAD

**Issue by zhanghuang515** [kangaroo1122/milo-spring-boot-starter#12]
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.edec.EdECObjectIdentifiers

**Comment by kangaroo1122** [comment]
看看是不是项目maven依赖冲突了，导致bcprov版本不对，这个和milo封装没关系。

**Comment by zhanghuang515** [comment]
冲突已解决，3q。java新手，我看maven repository 里 bcprov-jdk15on明明写的是1.69版本，引进来的却是1.59
