### ISSUE TITLE
报错：User limit of inotify instances reached or too many open files

### ISSUE THREAD

**Issue by zhanghuang515** [kangaroo1122/milo-spring-boot-starter#13]
在docker下运行一段时间后，opcua读取时会报错：User limit of inotify instances reached or too many open files

**Comment by kangaroo1122** [comment]
> 在docker下运行一段时间后，opcua读取时会报错：User limit of inotify instances reached or too many open files

3.0.6.12版本修复了，看看是不是用的这个版本

**Comment by zhanghuang515** [comment]
> > 在docker下运行一段时间后，opcua读取时会报错：User limit of inotify instances reached or too many open files
> 
> 3.0.6.12版本修复了，看看是不是用的这个版本

好的，已更新至新版本，再观察一下

**Comment by dwLamp** [comment]
@kangaroo1122 这个问题是将如下类中的如下代码注释掉就不会出现了吗？

**Comment by dwLamp** [comment]
@kangaroo1122 作者您好，我之前用的版本是3.0.5，我将MiloAutoConfiguration.java类中的如下代码注释掉，依然会报这个错(User limit of inotify instances reached or too many open files)，3.0.6.12版本还改了其他的代码吗？
// 多久执行一次对象扫描，将无用的对象销毁，默认-1不扫描
// poolConfig.setTimeBetweenEvictionRuns(Duration.ofMinutes(1));

**Comment by dwLamp** [comment]
@zhanghuang515 问下更新这个版本后，“User limit of inotify instances reached or too many open files”问题还报吗
