### ISSUE TITLE
订阅时如果节点有了增删改的处理办法

### ISSUE THREAD

**Issue by mikeJ133** [kangaroo1122/milo-spring-boot-starter#18]
我现在遇到了订阅时如果节点列表有了增删，该如何优雅的处理？
是不是有一种断开订阅，重新订阅的机制？  但是我在代码里没有发现，还希望作者给些提示。

**Comment by mikeJ133** [comment]
我使用了ScheduledExecutorService多线程，在节点列表有变化时，可以通过终止当前订阅线程并重新启动新的订阅线程来实现动态更新。

**Comment by mikeJ133** [comment]
作者还有什么更好的处理方式吗？

**Comment by kangaroo1122** [comment]
官方的包，是有增删的方法的，但是目前我工作比较忙，暂时没时间去维护，可能有空了我会去看看

**Comment by mikeJ133** [comment]
是的，使用官方的 subscription.createDataItems() 和 subscription.deleteDataItems()  可以实现。但是需要对Runner是否实例化做一些调整。我直接用了源码进行修改，不用pom了。

**Comment by kangaroo1122** [comment]
你也可以提个PR，我就直接合并进去了
