### ISSUE TITLE
java.util.NoSuchElementException: Timeout waiting for idle object, borrowMaxWaitMillis=1000

### ISSUE THREAD

**Issue by ShawnKion** [kangaroo1122/milo-spring-boot-starter#19]
写值会报这个错

**Comment by kangaroo1122** [comment]
> 写值会报这个错

你确定是这个工具的问题？

**Comment by ShawnKion** [comment]
我觉得是连接数不够用的，等不到可用连接报错

**Comment by kangaroo1122** [comment]
> 我觉得是连接数不够用的，等不到可用连接报错

连接池的大小不是可以配置的？？？

**Comment by ShawnKion** [comment]
连接池配置大了就会报
java.lang.InterruptedException: UaServiceFaultException: status=Bad_TooManySessions, message=The server has reached its maximum number of sessions.

**Comment by kangaroo1122** [comment]
> 连接池配置大了就会报
> java.lang.InterruptedException: UaServiceFaultException: status=Bad_TooManySessions, message=The server has reached its maximum number of sessions.
> 

大了是多大呢？kepware最多支持128个连接

**Comment by ShawnKion** [comment]
OPC server只支持5个session的连接

**Comment by ShawnKion** [comment]
![image](https://github.com/user-attachments/assets/f6c64c5f-01b7-4fce-a326-d81f1fbb5616)

**Comment by ShawnKion** [comment]
![image](https://github.com/user-attachments/assets/331de107-de64-4196-962e-d9398a950b2e)


> > 连接池配置大了就会报
> > java.lang.InterruptedException: UaServiceFaultException: status=Bad_TooManySessions, message=The server has reached its maximum number of sessions.
> 
> 大了是多大呢？kepware最多支持128个连接

**Comment by kangaroo1122** [comment]
不要超过服务器允许的连接数，服务器限制，和工具关系不大
