### ISSUE TITLE
程序停止运行后，好像没有走销毁方法呢

### ISSUE THREAD

**Issue by JiaShengLiao** [kangaroo1122/milo-spring-boot-starter#23]
![image](https://github.com/user-attachments/assets/400a9b55-51ab-4ab5-a4ca-b6edcf2eb9e0)

**Comment by kangaroo1122** [comment]
<img width="853" alt="image" src="https://github.com/user-attachments/assets/27b5defd-9e4c-4eaf-9175-0080aea045d2">
