### ISSUE TITLE
动态添加删除server

### ISSUE THREAD

**Issue by ghost** [kangaroo1122/milo-spring-boot-starter#3]
老哥，动态添加删除server啥时候搞呀？ 也可以说一下思路，我自己写一下

**Comment by kangaroo1122** [comment]
动态新增或删除订阅点位吗？如果是这个的话，周末看看，上班期间不搞这个

**Comment by ghost** [comment]
是动态添加和动态删除Server，因为已经修改了你的代码，是读取数据库中的Server信息进行连接，每个Server都会初始化多个对象。但是程序会涉及到动态添加和动态删除Server，我用了事件的监听来做的这个操作，是直接操作的initPool这个方法。目前看情况是实现了我这个需求

**Comment by kangaroo1122** [comment]
> 是动态添加和动态删除Server，因为已经修改了你的代码，是读取数据库中的Server信息进行连接，每个Server都会初始化多个对象。但是程序会涉及到动态添加和动态删除Server，我用了事件的监听来做的这个操作，是直接操作的initPool这个方法。目前看情况是实现了我这个需求

哦哦，数据库加载，行，那实现了就行。

**Comment by bobocha214** [comment]
> 是动态添加和动态删除Server，因为已经修改了你的代码，是读取数据库中的Server信息进行连接，每个Server都会初始化多个对象。但是程序会涉及到动态添加和动态删除Server，我用了事件的监听来做的这个操作，是直接操作的initPool这个方法。目前看情况是实现了我这个需求

老哥有demo吗，我最近也需要这个动态添加server，准备将所有server展现在前端，希望能给我个demo参考参考，有测试过能承受多少台吗

**Comment by kangaroo1122** [comment]
> > 是动态添加和动态删除Server，因为已经修改了你的代码，是读取数据库中的Server信息进行连接，每个Server都会初始化多个对象。但是程序会涉及到动态添加和动态删除Server，我用了事件的监听来做的这个操作，是直接操作的initPool这个方法。目前看情况是实现了我这个需求
> 
> 老哥有demo吗，我最近也需要这个动态添加server，准备将所有server展现在前端，希望能给我个demo参考参考，有测试过能承受多少台吗

看看readme最后介绍满足需求不
