### ISSUE TITLE
KeyStoreLoader   需要特定配置吗

### ISSUE THREAD

**Issue by ghost** [kangaroo1122/milo-spring-boot-starter#5]
KeyStoreLoader  这个在创建客户端时到底是不是必要的？

SelfSignedCertificateBuilder builder = new SelfSignedCertificateBuilder(keyPair)
                    .setCommonName("Milo Client")
                    .setOrganization("siemens")
                    .setOrganizationalUnit("dev")
                    .setLocalityName("Folsom")
                    .setStateName("CA")
                    .setCountryCode("US")
                    .setApplicationUri("urn:kangaroohy:milo:client")
                    .addDnsName("localhost")
                    .addIpAddress("127.0.0.1");

这些参数需不需要根据实际情况进行修改？

我们现在遇到一个问题是[remote=/139.24.230.201:53530] Received error message: ErrorMessage{error=StatusCode{name=Bad_SecurityChecksFailed, value=0x80130000, quality=bad}, reason=Bad_SecurityChecksFailed (code=0x80130000, description="An error occurred verifying security.")}

这是线上模拟器的地址，但是本地我的模拟器就链接正常

**Comment by kangaroo1122** [comment]
> KeyStoreLoader 这个在创建客户端时到底是不是必要的？
> 
> SelfSignedCertificateBuilder builder = new SelfSignedCertificateBuilder(keyPair) .setCommonName("Milo Client") .setOrganization("siemens") .setOrganizationalUnit("dev") .setLocalityName("Folsom") .setStateName("CA") .setCountryCode("US") .setApplicationUri("urn:kangaroohy:milo:client") .addDnsName("localhost") .addIpAddress("127.0.0.1");
> 
> 这些参数需不需要根据实际情况进行修改？
> 
> 我们现在遇到一个问题是[remote=/139.24.230.201:53530] Received error message: ErrorMessage{error=StatusCode{name=Bad_SecurityChecksFailed, value=0x80130000, quality=bad}, reason=Bad_SecurityChecksFailed (code=0x80130000, description="An error occurred verifying security.")}
> 
> 这是线上模拟器的地址，但是本地我的模拟器就链接正常

这是自签证书配置，你改了参数，也还是自签证书，看看服务器的安全策略是否和代码里配置的策略相同。
