### ISSUE TITLE
报证书错误，我是用的匿名，该如何解决，UaException: status=Bad_SecurityChecksFailed, message=Certificate is not trusted.

### ISSUE THREAD

**Issue by bobocha214** [kangaroo1122/milo-spring-boot-starter#7]

**Comment by kangaroo1122** [comment]
看看kepware的允许匿名配置是否关闭了[https://blog.csdn.net/Vampire_1122/article/details/119025477](https://blog.csdn.net/Vampire_1122/article/details/119025477)

**Comment by bobocha214** [comment]
> 看看kepware的允许匿名配置是否关闭了https://blog.csdn.net/Vampire_1122/article/details/119025477

我并没有使用kepware,我是用的是easyopc做的本地服务，在uaexpert中可以用匿名方式正常访问，我下午使用kepware试一下
